Backend/Core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from Core.views import imprimir,index,robots,categoria,desenho,add_to_favorito,favoritos,about,politica,ads,transparencia,contact,remove_from_favorito,formulario,unsubscriber,enviar_emeil,Sitemap


app_name = 'Core'

sitemaps = {
    'sitemap': Sitemap,
}

urlpatterns = [
    path('',view=index,name='index'),
    path('categoria/<str:nome>',view=categoria,name='categoria'),
    path('desenho/<str:nome>',view=desenho,name='desenho'),
    path('add_to_favorito/<item>', view=add_to_favorito, name='add_to_favorito'),
    path('remove_from_favorito/<item>', view=remove_from_favorito, name='remove_from_favorito'),
    path('favoritos/',view=favoritos,name='favoritos'),
    path('about/',view=about,name='about'),
    path('politica/',view=politica,name='politica'),
    path('transparencia/',view=transparencia,name='transparencia'),
    path("contact/", view=contact, name='contact'),
    path('imprimir/<int:id>',view=imprimir, name='imprimir'),
    path('ads.txt',ads),
    path('enviar_emeil/',view=enviar_emeil, name='enviar_emeil'),
    path("formulario/", view=formulario, name='formulario'),
    path('unsubscriber/<int:id>',view=unsubscriber, name='unsubscriber'),
    path('sitemap.xml',sitemap, {'sitemaps': sitemaps}),
    path('robots.txt',robots),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/Word/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('',include('Core.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/Core/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.utils.safestring import mark_safe
from django.urls import reverse

class Categoria(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Imagem(models.Model):
    nome = models.CharField(max_length=255)
    categoria = models.ForeignKey(Categoria,null=True, blank=True, on_delete=models.DO_NOTHING, db_index=True)
    arquivo = models.ImageField(upload_to='Imagens')
    descricao = models.TextField(blank=True)
    data_upload = models.DateTimeField(auto_now_add=True)
    afiliado= RichTextField(max_length=3000, null=True, blank=True)
    destaque= models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('Core:desenho', args=[str(self.nome)]) 

    @mark_safe
    def icone(self):
        return f'<img width="30px" src="{self.arquivo.url}">'

    def __str__(self):
        return self.nome
    
    class Meta:
        verbose_name_plural = "Desenhos"

class Contato(models.Model):
    Nome = models.CharField(max_length=100,null=True, blank=True)
    Email = models.EmailField()
    Telefone = models.IntegerField()
    Mensagem = models.TextField(max_length=500)
    Lido = models.BooleanField(default=False)
    
    def __str__(self):
        return self.Nome
    
    class Meta:
        verbose_name_plural = "Contatos"

class Email(models.Model):
    email = models.EmailField()
    ativo = models.BooleanField(default=True)

    def __str__(self) -> str:
        return self.email
    
    class Meta:
        verbose_name_plural = "Newsletter"

Backend/Core/views.py
import datetime
from .models import Imagem,Categoria,Contato,Email
from django.contrib.auth.decorators import login_required
from .utils import email_html
from django.shortcuts import  render,redirect,get_object_or_404
from django.core.paginator import Paginator
import os
from django.conf import settings
from django.http import HttpResponse
from django.views.decorators.cache import cache_page
from django.core.cache import cache
from django.db.models import Count
from django.contrib import sitemaps
from PIL import Image
import io
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter
from django.http import FileResponse,JsonResponse
from django.contrib import messages
from django.contrib.messages import constants
import logging

logger = logging.getLogger('MyApp')

def get_categorias_com_contagem():
    cached_categorias = cache.get('all_categorias_com_contagem')
    if cached_categorias is None:
        categorias = Categoria.objects.annotate(quantidade=Count('imagem')).values('id', 'nome', 'quantidade')
        cached_categorias = [{'id': cat['id'], 'nome': cat['nome'], 'quantidade': cat['quantidade']} for cat in categorias]
        cache.set('all_categorias_com_contagem', cached_categorias, timeout=1800)
    return cached_categorias

def index(request):
     categorias = get_categorias_com_contagem()
     imagens = Imagem.objects.only('nome','arquivo','descricao').filter(destaque=True).all().order_by('-id')
     pagina = Paginator(imagens,25)
     pg_number = request.GET.get('page')
     imgs = pagina.get_page(pg_number)
     return render(request,'index.html',{'imagens':imgs,'categorias':categorias,})

def categoria(request,nome):
     categoria_nome = get_object_or_404(Categoria, nome=nome)
     categorias = get_categorias_com_contagem()
     imagens = Imagem.objects.only('nome','arquivo','descricao').filter(categoria=categoria_nome).order_by('-id')
     pagina = Paginator(imagens,25)
     pg_number = request.GET.get('page')
     imgs = pagina.get_page(pg_number)
     return render(request,'categoria.html',{'imagens':imgs,'categorias':categorias,})

def desenho(request,nome):
     categorias = get_categorias_com_contagem()
     img = Imagem.objects.filter(nome=nome)
     return render(request,'desenho.html',{'img':img,'categorias':categorias,})


def add_to_favorito(request, item):
    favoritos = request.session.get('favoritos', [])
    favoritos.append(item)
    request.session['favoritos'] = favoritos
    return HttpResponse(status=204)

def remove_from_favorito(request, item):
    favoritos = request.session.get('favoritos', [])
    if item in favoritos:
        favoritos.remove(item)
        request.session['favoritos'] = favoritos
        return redirect('/favoritos')
    else:
        return JsonResponse({'error': 'Item não encontrado nos favoritos'}, status=404)

def favoritos(request):
    categorias = get_categorias_com_contagem()
    favoritos = request.session.get('favoritos', [])
    request.session['favoritos'] = favoritos
    return render(request, 'favoritos.html', {'categorias':categorias,'favoritos': favoritos})

@cache_page(60 * 100)
def about(request):
     categorias = get_categorias_com_contagem()
     return render(request,'about.html',{'categorias':categorias,})

def contact(request):
    if request.method == "GET":
        categorias = get_categorias_com_contagem()
        status = request.GET.get('status')
        return render(request,'contact.html',{'status':status,'categorias':categorias})
    else:
        NOME = request.POST.get('name')
        EMAIL = request.POST.get('email')
        TELEFONE = request.POST.get('phone')
        MENSAGEM = request.POST.get('message')
        
        new_contato= Contato(
            Nome=NOME,
            Email=EMAIL,
            Telefone=TELEFONE,
            Mensagem=MENSAGEM
        )
        new_contato.save()
        messages.add_message(request, constants.SUCCESS, 'Enviado com sucesso')
        return redirect("/")

@cache_page(60 * 100)
def politica(request):
     categorias = get_categorias_com_contagem()
     return render(request,'politica-de-privacidade.html',{'categorias':categorias,})

@cache_page(60 * 100)
def transparencia(request):
     categorias = get_categorias_com_contagem()
     return render(request,'transparencia.html',{'categorias':categorias,})

def imprimir(request,id):
        try:
            image = Imagem.objects.get(id=id)
            buffer = io.BytesIO()
            PDF = canvas.Canvas(buffer, pagesize=letter)

            # Abre a imagem usando PIL
            img_path = os.path.join(settings.BASE_DIR, 'media', f'{image.arquivo}')
            img = Image.open(img_path)

            # Converte a imagem para preto e branco
            img = img.convert("L")

            # Obtém as dimensões da folha A4
            a4_width, a4_height = letter

            # Calcula as proporções para manter a escala
            width_ratio = a4_width / img.width
            height_ratio = a4_height / img.height
            min_ratio = min(width_ratio, height_ratio)

            # Calcula as novas dimensões da imagem mantendo a escala
            new_width = int(img.width * min_ratio)
            new_height = int(img.height * min_ratio)

            # Calcula as coordenadas para centralizar a imagem na folha
            x_offset = (a4_width - new_width) / 2
            y_offset = (a4_height - new_height) / 2

            # Desenha a imagem na folha A4 mantendo a escala
            PDF.drawInlineImage(img, x_offset, y_offset, width=new_width, height=new_height)
            PDF.drawString(120,2,'Visite https://mundocoloridokids.com.br para mais desenhos')

            PDF.showPage()
            PDF.save()

            buffer.seek(0)
            response = FileResponse(buffer, as_attachment=True, filename='Mundo Colorido Kids - Desenho.pdf')
            response.status_code = 200
            return response
        except Exception as msg:
            response = msg


@cache_page(60 * 100)
def robots(request):
    if not settings.DEBUG:
        path = os.path.join(settings.STATIC_ROOT,'robots.txt')
        with open(path,'r') as arq:
            return HttpResponse(arq, content_type='text/plain')
    else:
        path = os.path.join(settings.BASE_DIR,'templates/static/robots.txt')
        with open(path,'r') as arq:
            return HttpResponse(arq, content_type='text/plain')

@cache_page(60 * 100)
def ads(request):
    if not settings.DEBUG:
        path = os.path.join(settings.STATIC_ROOT,'ads.txt')
        with open(path,'r') as arq:
            return HttpResponse(arq, content_type='text/plain')
    else:
        path = os.path.join(settings.BASE_DIR,'templates/static/ads.txt')
        with open(path,'r') as arq:
            return HttpResponse(arq, content_type='text/plain')


def formulario(request):
    if request.method =="POST":
        email = request.POST.get('email')
        valida = Email.objects.filter(email=email)
        if valida.exists():
            messages.add_message(request, constants.ERROR, 'Email Ja cadastrado')
            logger.info(f'Email Ja cadastrado {email} '+str(datetime.datetime.now())+' horas!')
            return redirect("/")
        cadastrar = Email.objects.create(
            email=email
        )
        cadastrar.save()
        messages.add_message(request, constants.SUCCESS, 'Cadastrado com sucesso')
        return redirect("/")
    
def unsubscriber(request,id):
    email = Email.objects.get(id=id)
    email.ativo =False
    email.save()
    return HttpResponse('Cancelado sua Inscriçao')

@login_required(login_url='/admin/login/?next=/admin/') 
def enviar_emeil(request):
    try:
        path_template = os.path.join(settings.BASE_DIR, 'Core/templates/emails/email.html')
        base_url = request.build_absolute_uri('/')
        emails = Email.objects.filter(ativo=True).all()
        posts = Imagem.objects.only('nome','descricao').filter(destaque=True).all().order_by('-id')[:15]

        for email in emails:
            email_html(path_template, 'Novos Desenhos', [email,],posts=posts,email=email,base_url=base_url)
            messages.add_message(request, constants.SUCCESS, 'Emais enviados com sucesso')
            return redirect("/")
        
    except Exception as msg:
        messages.add_message(request, constants.ERROR, f'Nao foi possivel enviar os Emails consulte o arquivo de Log')
        logger.critical(f'{msg} '+str(datetime.datetime.now())+' horas!')
        return redirect("/")

 
class Sitemap(sitemaps.Sitemap):
    i18n = True
    changefreq ='monthly'
    priority = 0.7

    def items(self):
        return Imagem.objects.all()        

    def lastmod(self, obj):
        return obj.data_upload

Backend/Core/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}
Sobre
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}


{% block 'body' %}
<div class="about">
    <h1 class="text-center">Mundo Colorido Kids</h1>
    <main class="mb-4">

        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7 about">
                    <p>
                        No nosso cantinho especial, a magia da criatividade ganha vida! Aqui, cada desenho é uma porta para um universo cheio de cores, aventuras e sorrisos. 🌈✨
                    </p>
                    <br>
                    <p>
                        Ficamos felizes em fazer parte desse momento especial na vida das crianças, fazendo de cada página um convite para explorar, aprender e, claro, se divertir. Junte-se a nós nesta aventura onde a magia das cores encontra a pureza da infância. 🎨🚀
                    </p>
                </div>
            </div>
        </div>
    </main>
</div>
<script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>
{% endblock %}

Backend/Core/templates/categoria.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}
Por Categoria
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}


{% block 'body' %}
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for img in imagens %}
        <div class="card text-center carde" style="width: 20rem;">
            <img src="{{img.arquivo.url}}" class="card-img-top" alt="{{img.arquivo.url}}">
            <div class="card-body">
                <h5 class="card-title">{{img.nome}}</h5>
                <p class="card-text">{{img.descricao}}</p>
                <a href="{% url 'Core:desenho' img.nome %}" class="btn btn-success">Ver</a>
                <a href="{% url 'Core:add_to_favorito' img.nome %}" id="btnAdicionar"><img width="30" height="30" src="https://img.icons8.com/stickers/100/add-bookmark.png" alt="add-bookmark"/></a>
            </div>
        </div>
        {%endfor%}
    </div>
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if imagens.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ imagens.previous_page_number }}">Voltar</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="#">{{ imagens.number }}:{{ imagens.paginator.num_pages }}</a></li>
          {% if imagens.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ imagens.next_page_number }}">Proximo</a></li>
          {% endif %}
        </ul>
      </nav>
</div>
<script src="{% static 'js/script.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var btnAdicionarFavoritos = document.getElementById('btnAdicionar');
    btnAdicionarFavoritos.addEventListener('click', function() {
        alert('Adicionado aos Favoritos');
    });
});
</script>
<script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>
{% endblock %}

Backend/Core/templates/contact.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}
Contatos
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}

 {% block 'body' %}
 <br>
 <div class="container-fluid">
    <div class="justify-content-center text-center">
        <main class="mb-4">
            <div class="container px-4 px-lg-5">
                <div class="row gx-4 gx-lg-5 justify-content-center">
                    <div class="col-md-10 col-lg-8 col-xl-7">
                       <p style="color:#fff"> Quer entrar em contato? Preencha o formulário abaixo para me enviar uma mensagem e entrarei em contato com você o mais breve possível!</p>
                        <div class="my-5">
                            <form method="POST"  id="contactForm" action="{% url 'Core:contact'%}">{% csrf_token %}
                                <div class="form-floating">
                                    <input class="form-control" id="name" name="name" type="text" placeholder="Entre com seu Nome" required  />
                                    <label for="name" style="color:#fff">Nome</label>
                                    <div class="invalid-feedback" data-sb-feedback="name:required">Um nome e Obrigatorio!</div>
                                </div>
                                <br>
                                <div class="form-floating">
                                    <input class="form-control" id="email" name="email" type="email" placeholder="Entre com seu email..." required />
                                    <label for="email" style="color:#fff">Endereco de Email</label>
                                    <div class="invalid-feedback" data-sb-feedback="email:required">Um email e Obrigatorio!.</div>
                                    <div class="invalid-feedback" data-sb-feedback="email:email">Email nao valido.</div>
                                </div>
                                <br>
                                <div class="form-floating">
                                    <input class="form-control" id="phone" name="phone" type="tel" placeholder="Entre com seu Telefone..." required />
                                    <label for="phone" style="color:#fff">Telefone</label>
                                    <div class="invalid-feedback" data-sb-feedback="phone:required">Um Telefone e Obrigatorio!</div>
                                </div>
                                <br>
                                <div class="form-floating">
                                    <textarea class="form-control" id="message" name="message" placeholder="Entre com sua Mensagem aqui..." style="height: 12rem" rows="4" cols="50" maxlength="500" required></textarea>
                                    <br>
                                    <label for="message" style="color:#fff">Mensagem</label>
                                    <div class="invalid-feedback" data-sb-feedback="message:required">Uma mensagem e Obrigatorio</div>
                                </div>
                                <br/>
                                <div class="text-center">
                                <button class="btn btn-success text-uppercase" id="submitButton" type="submit">Enviar</button>
                            </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </main>
 </div>
 <script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>
 {% endblock %}

Backend/Core/templates/desenho.html
{% extends 'base.html' %}
{% load static %}

{% block 'title' %}
Desenho
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}


{% block 'body' %}
<div class="container-fluid">
    <br>
    {% for i in img %}
    <div class="Desenho row justify-content-center">
        <div class="card" style="width: 45rem;">
            <br>
            <a href="/" class="text-center">&lt; Voltar</a>
            <img class="img-fluid tamanho" src="{{i.arquivo.url}}" alt="Imagem de capa do card">
            <div class="card-body">
                <h5 class="card-title text-center">{{i.nome}}</h5>
                <p class="card-text text-center">{{i.descricao}}</p>
                {% if i.afiliado %}
                <div class="filiado">{{i.afiliado|safe}}</div>
                {% else %}
                {% endif %}
                <div class="text-center">
                    <a href="{% url 'Core:imprimir' i.id %}" download="NomeDoArquivo" class="btn btn-success">Baixar</a>
                </div>
            </div>
        </div>
    </div>
    <br>
    {% endfor %}
</div>

<script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>
{% endblock %}

Backend/Core/templates/favoritos.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}
Favoritos
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}

{% block 'body' %}
<div class="row justify-content-center">

  

<div class="list-group fav">
        <h1 style="color:#fff">Meus Favoritos</h1>
        {% for item in favoritos %}
      
        <ul class="list-group">
         <li class="list-group-item"><a class="card-link" href="{% url 'Core:desenho' item %}">{{ item }}</a> <a class="card-link" href="{% url 'Core:remove_from_favorito' item %}" id="btnremoveFavoritos"><img width="30" height="30" src="https://img.icons8.com/color/48/delete-sign--v1.png" alt="delete-sign--v1"/></a></li>
        </ul>

        {% endfor %}
      </div>

</div>

<script src="{% static 'js/script.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var btnAdicionarFavoritos = document.getElementById('btnremoveFavoritos');
    btnAdicionarFavoritos.addEventListener('click', function() {
        alert('Removido dos Favoritos');
    });
});
</script>

<script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>
{% endblock %}

Backend/Core/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block 'title' %}
{% trans "Pagina Inicial" %}
{% endblock %}

 {% block 'cabeca' %}
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}


{% block 'body' %}
<div class="container-fluid">
    <div class="row justify-content-center">
        {% for img in imagens %}
        <div class="card text-center carde" style="width: 20rem;">
            <span class="badge badge-danger">{% trans "Em Alta" %}</span>
            <img src="{{img.arquivo.url}}" class="card-img-top" alt="{{img.arquivo.url}}">
            <div class="card-body">
                <h5 class="card-title">{{img.nome}}</h5>
                <p class="card-text">{{img.descricao}}</p>
                <a href="{% url 'Core:desenho' img.nome %}" class="btn btn-success">{% trans "Ver" %}</a>
                <a href="{% url 'Core:add_to_favorito' img.nome %}" id="btnAdicionarFavoritos"><img width="30" height="30" src="https://img.icons8.com/stickers/100/add-bookmark.png" alt="add-bookmark"/></a>
            </div>
        </div>
        {%endfor%}
    </div>
    <br>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if imagens.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ imagens.previous_page_number }}">{% trans "Voltar" %}</a></li>
          {% endif %}
          <li class="page-item"><a class="page-link" href="#">{{ imagens.number }}:{{ imagens.paginator.num_pages }}</a></li>
          {% if imagens.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ imagens.next_page_number }}">{% trans "Proximo" %}</a></li>
          {% endif %}
        </ul>
      </nav>
</div>
<script src="{% static 'js/script.js' %}"></script>
<script>
    document.addEventListener('DOMContentLoaded', function() {
    var btnAdicionarFavoritos = document.getElementById('btnAdicionarFavoritos');
    btnAdicionarFavoritos.addEventListener('click', function() {
        alert('Adicionado aos Favoritos');
    });
});
</script>

<script type="text/javascript">
    var app_url = 'https://cloaking.link/';
    var app_api_token = '216e007affc2d54531e15df85161c32bb072c578';
    var app_advert = 2;
    var app_domains = ["https://mundocoloridokids.com.br/","*.mundocoloridokids.com.br/"];
</script>
<script src='//cloaking.link/js/full-page-script.js'></script>

{% endblock %}

Backend/Core/templates/transparencia.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}
Transparência - Mundo Colorido Kids
{% endblock %}

 {% block 'cabeca' %}
<!-- adsense tags -->
<meta name="google-adsense-account" content="ca-pub-1825430354660819">
<script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-1825430354660819"
        crossorigin="anonymous"></script>
 {% endblock %}

 {% block 'body' %}
 <br>
 <div class="container-fluid">
    <div class="justify-content-center politica text-center">
        <br>
        <span class="destaque"><h1>Transparência - Mundo Colorido Kids</h1></span>
        <br>
        <br>
        Bem-vindo à nossa página de Transparência no <a href="{% url 'Core:index'  %}" target="_blank" rel="noopener noreferrer">Mundo Colorido Kids!</a> Estamos comprometidos em fornecer informações claras e abertas sobre como operamos e interagimos com você, nosso valioso visitante.
        <br>
        <br>
        <span class="destaque">Origem dos Artigos:</span>
        <br>
        <br>
        Nossos artigos são gerados pela nossa equipe qualificada no Mundo Colorido Kids, composta por especialistas em educação infantil, artistas gráficos e redatores. Utilizamos também ferramentas de Inteligência Artificial (IA) para criar conteúdo envolvente e relevante. Além disso, colaboramos com profissionais e especialistas para garantir a qualidade do nosso material.
        <br>
        <br>
        <span class="destaque">Fonte das Imagens:</span>
        <br>
        <br>
        As imagens utilizadas em nosso site geralmente são de domínio público ou licenciadas para uso comercial e Inteligência Artificial (IA). Quando possível, fornecemos créditos às fontes originais das imagens. Caso você seja o detentor dos direitos de alguma imagem e sinta que ela foi usada indevidamente, entre em contato conosco para resolvermos a situação.
        <br>
        <br>
        <span class="destaque">Afiliados e Publicidades:</span>
        <br>
        <br>
        Podemos receber compensação por recomendar produtos ou serviços por meio de links de afiliados. Isso ajuda a sustentar o funcionamento do site. As publicidades exibidas são cuidadosamente escolhidas para serem relevantes ao nosso público-alvo.
        <br>
        <br>
        <span class="destaque">Política de Privacidade:</span>
        <br>
        <br>
        Nossa política de privacidade está disponível em <a href="{% url 'Core:politica'  %}" target="_blank" rel="noopener noreferrer">link</a>. Detalhamos como coletamos, usamos e protegemos suas informações pessoais ao utilizar nosso site.
        <br>
        <br>
        <span class="destaque">Contato:</span>
        <br>
        Estamos aqui para ouvir você! Se tiver alguma dúvida, sugestão ou preocupação, entre em contato conosco envie um e-mail para santosgomesv@gmail.com.
        <br>
        Agradecemos por fazer parte da nossa comunidade no Mundo Colorido Kids!
        <br>
        Última atualização: 23/01/2024
    </div>
    <br>
 </div>

 {% endblock %}