Backend/Core/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from Core.views import imprimir,index,robots,categoria,desenho,add_to_favorito,favoritos,about,politica,ads,transparencia,contact,remove_from_favorito,formulario,unsubscriber,enviar_emeil,Sitemap


app_name = 'Core'

sitemaps = {
    'sitemap': Sitemap,
}

urlpatterns = [
    path('',view=index,name='index'),
    path('categoria/<str:nome>',view=categoria,name='categoria'),
    path('desenho/<str:nome>',view=desenho,name='desenho'),
    path('add_to_favorito/<item>', view=add_to_favorito, name='add_to_favorito'),
    path('remove_from_favorito/<item>', view=remove_from_favorito, name='remove_from_favorito'),
    path('favoritos/',view=favoritos,name='favoritos'),
    path('about/',view=about,name='about'),
    path('politica/',view=politica,name='politica'),
    path('transparencia/',view=transparencia,name='transparencia'),
    path("contact/", view=contact, name='contact'),
    path('imprimir/<int:id>',view=imprimir, name='imprimir'),
    path('ads.txt',ads),
    path('enviar_emeil/',view=enviar_emeil, name='enviar_emeil'),
    path("formulario/", view=formulario, name='formulario'),
    path('unsubscriber/<int:id>',view=unsubscriber, name='unsubscriber'),
    path('sitemap.xml',sitemap, {'sitemaps': sitemaps}),
    path('robots.txt',robots),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/Word/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path('',include('Core.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Backend/templates/base.html
{% load static %}
{% load cache %}

{% cache 3600 cache_meta-1 %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="{% static 'img/logo.webp' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta property="og:title" content="Mundo Colorido Kids" />
    <meta property="og:type" content="website" />
    <meta property="og:image" content="{% static 'img/logo.webp' %}" />
    <meta property="og:url" content="." />
    <meta property="og:site_name" content="Mundo Colorido Kids" />
    <meta property="og:description"
          content="Explore o mundo colorido da criatividade com desenhos para colorir do Mundo Colorido Kids. Deixe as crianças expressarem sua imaginação com nossa vasta coleção de desenhos divertidos e educativos." />
    <meta name="Title"
          content="Mundo Colorido Kids" />
    {% endcache %}

    {% block 'cabeca' %}
    {% endblock %}
    <title>
        {% block 'title' %}
        {% endblock %}
    </title>
    {% cache 3600 cache_meta %}
    <meta name="Author" content="Vitor Gomes" />
    <meta name="description"
          content="Explore o mundo colorido da criatividade com desenhos para colorir do Mundo Colorido Kids. Deixe as crianças expressarem sua imaginação com nossa vasta coleção de desenhos divertidos e educativos.">
    <meta name="KeyWords"
          content="desenhos para colorir, crianças, atividades infantis, educação, criatividade, diversão, aprendizado" />
    <meta name="generator" content="Microsoft FrontPage 5.0" />
    <meta name="Language" CONTENT="Portuguese" />
    <meta name="Rating" CONTENT="Safe For Kids" />
    <meta name="Doc-class" CONTENT="Completed" />
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-GY92YJ63M8"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag() { dataLayer.push(arguments); }
        gtag('js', new Date());

        gtag('config', 'G-GY92YJ63M8');
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link href="{% static 'css/css.css' %}" rel="stylesheet" />
    <script src="{% static 'js/cookes.js' %}"></script>
    {% endcache %}
    <nav class="navbar navbar-expand-lg navbar-color" style="color:beige">
        <a class="navbar-brand" href="#"><img src="{% static 'img/logo.webp' %}" alt="logo" width="60" height="60"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"><img width="48" height="48" src="https://img.icons8.com/fluency/48/menu--v1.png" alt="menu--v1" /></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'Core:index'%}">Home<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                        Categorias
                    </a>
                    <div class="dropdown-menu">
                        {% for categoria in categorias %}
                        <a class="dropdown-item" href="{% url 'Core:categoria' categoria.nome %}">{{categoria.nome}} <span class="badge badge-danger">{{categoria.quantidade}}</span></a>
                        {% endfor %}
                    </div>
                </li>
                {% cache 3600 cache_menu %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Core:about'%}">Sobre Nós</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Core:contact'%}">Contato</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Core:politica'  %}">Política de Privacidade</a>
                </li>
                {% endcache %}
                {% if user.is_superuser %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index'  %}">ADMIN</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'Core:enviar_emeil'  %}">Disparar Email</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <a href="{% url 'Core:favoritos' %}"><img width="30" height="30" src="https://img.icons8.com/color/48/bookmark-ribbon--v1.png" alt="bookmark-ribbon--v1"/></a>
        <form id="search-form" class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" id="search-input" placeholder="Carro..." aria-label="Search">
            <button class="btn btn-outline-primary my-2 my-sm-0" type="button" id="search-button">Pesquisar</button>
        </form>
    </nav>
</head>
  <body>
    {% block 'body' %}
	{% endblock %}
    <div class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="text-center alert {{message.tags}}">
                    {{message}}
                </div>
            {% endfor %}
        {% endif %}
    </div>
    {% cache 3600 cache_footer %}
    <div class="newsletter-subscribe mt-5 container">
        <div class="container">
            <div class="intro">
                <h2 class="text-center newsletter">Assine a nossa newsletter</h2>
                <p class="text-center">Fique por dentro das novidades,e muito mais. Sua jornada começa aqui, com um clique. Inscreva-se agora e nunca perca uma atualização!" 🚀📨💡</p>
            </div>
            <form  action="{% url 'Core:formulario' %}" class="form-inline" method="post">{% csrf_token %} 
                <div class="form-group"><input class="form-control" type="email" name="email" placeholder="Seu Email"></div>
                <div class="form-group"><button class="btn btn-primary" type="submit">Se inscrever</button></div>
            </form>
        </div>
    </div>
  <footer>
    <nav class="text-center p-4 navbar-color">
      <p>Copyright 2024 Todos os direitos reservados</p>
  </nav>
  <div id="cookie-popup" class="cookie-popup">
    <p>Utilizamos cookies para melhorar o desempenho e segurança do site, além de personalizar conteúdo e anúncios. Ao navegar neste site, você concorda com a nossa <a href="{% url 'Core:politica'  %}" target="_blank" rel="noopener noreferrer">Política Privacidade</a> e <a href="{% url 'Core:transparencia'  %}" target="_blank" rel="noopener noreferrer">Trasparencia</a></p>
    <button id="cookie-accept">Aceitar</button>
</div>
  </footer>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
  {% endcache %}
  <style>
    .newsletter-subscribe {
        color: #313437;
        background-color: #ffffff;
        padding: 55px 74px;
        }

        .newsletter-subscribe p {
        color:var(--bage);
        line-height: 1.5;
        }

        .newsletter-subscribe h2 {
        font-size: 24px;
        font-weight: bold;
        margin-bottom: 25px;
        line-height: 1.5;
        padding-top: 0;
        margin-top: 0;
        color: inherit;
        }

.newsletter-subscribe .intro {
        font-size: 16px;
        max-width: 500px;
        margin: 0 auto 25px;
        }

.newsletter-subscribe .intro p {
        margin-bottom: 35px;
}

.newsletter-subscribe form {
        justify-content: center;
}

.newsletter-subscribe form .form-control {
            background: #eff1f4;
            border: none;
            border-radius: 3px;
            box-shadow: none;
            outline: none;
            color: inherit;
            text-indent: 9px;
            height: 45px;
            margin-right: 10px;
            min-width: 250px;
            }

.newsletter-subscribe form .btn {
            padding: 16px 32px;
            border: none;
            background: none;
            box-shadow: none;
            text-shadow: none;
            opacity: 0.9;
            text-transform: uppercase;
            font-weight: bold;
            font-size: 13px;
            letter-spacing: 0.4px;
            line-height: 1;
            }

.newsletter-subscribe form .btn:hover {
            opacity: 1;
            }

.newsletter-subscribe form .btn:active {
            transform: translateY(1px);
            }

.newsletter-subscribe form .btn-primary {
            background-color: var(--azul-celeste) !important;
            color: #fff;
            outline: none !important;
            }
.newsletter {
color: var(--azul-celeste) !important;
}
</style>
</html>